extensions/kubeapi/rbac/create.go
extensions/kubeapi/rbac/list.go

Accidentally used the wrong import in the rbac extensions.

[v2.7] Updated to use correct import.

---

extensions/pipeline/releaseupgrade.go

Back port of https://github.com/rancher/shepherd/pull/32

[2.8]Adding helm extra setting to pipeline

---

extensions/pipeline/releaseupgrade.go

Back port of https://github.com/rancher/shepherd/pull/32

[2.7] Adding helm extra setting to pipeline

---

extensions/machinepools/amazonec2_machine_config.go
extensions/machinepools/azure_machine_config.go
extensions/machinepools/digitalocean_machine_config.go
extensions/machinepools/harvester_machine_config.go
extensions/machinepools/linode_machine_config.go
extensions/machinepools/machinepools.go
extensions/machinepools/vsphere_machine_config.go
extensions/pipeline/configuration.go
extensions/provisioning/creates.go
extensions/provisioning/providers.go

previously in: https://github.com/rancher/rancher/pull/43775
everything is being pulled out from framework/

allow multiple configs for rke2/k3s node drivers

---

extensions/machinepools/amazonec2_machine_config.go
extensions/machinepools/azure_machine_config.go
extensions/machinepools/digitalocean_machine_config.go
extensions/machinepools/harvester_machine_config.go
extensions/machinepools/linode_machine_config.go
extensions/machinepools/machinepools.go
extensions/machinepools/vsphere_machine_config.go
extensions/pipeline/configuration.go
extensions/provisioning/creates.go
extensions/provisioning/providers.go

backport of https://github.com/rancher/shepherd/pull/6

[2.7] multi-config

---

extensions/pipeline/releaseupgrade.go
extensions/upgradeinput/config.go
extensions/upgradeinput/load.go

Adds `upgradeinput` package with upgrade tests configuration and its load functions.

[2.7] Move Upgrade Test Configurations and Load Functions

---

extensions/defaults/defaults.go
extensions/kubeapi/projects/create.go
extensions/kubeapi/projects/delete.go
extensions/kubeapi/projects/list.go
extensions/kubeapi/projects/projects.go
extensions/kubeapi/projects/update.go
extensions/kubeapi/rbac/create.go
extensions/kubeapi/rbac/delete.go
extensions/kubeapi/rbac/list.go
extensions/kubeapi/rbac/rbac.go
extensions/kubeapi/rbac/update.go
extensions/rancherleader/rancherleader.go

https://github.com/rancher/qa-tasks/issues/1155
- Added helper functions to list, create, update, delete Projects using Public API. This was previously implemented in the following PR: https://github.com/rancher/rancher/pull/43670
- Added helper functions required to test Project Scoped Secrets feature (new feature introduced in 2.9)

Extensions required for managing projects using Public API

---

extensions/defaults/defaults.go
extensions/kubeapi/projects/create.go
extensions/kubeapi/projects/delete.go
extensions/kubeapi/projects/list.go
extensions/kubeapi/projects/projects.go
extensions/kubeapi/projects/update.go
extensions/kubeapi/rbac/create.go
extensions/kubeapi/rbac/delete.go
extensions/kubeapi/rbac/list.go
extensions/kubeapi/rbac/rbac.go
extensions/kubeapi/rbac/update.go
extensions/rancherleader/rancherleader.go

Backport : https://github.com/rancher/shepherd/pull/15

[2.8] Extensions required for managing projects using Public API 

---

extensions/pipeline/releaseupgrade.go

Updating configs to add repo urls to be able to have prime related charts

Adding helm repo URL in the config

---

extensions/pipeline/releaseupgrade.go

Back port of https://github.com/rancher/shepherd/pull/68

[2.8] Adding helm repo URL in the config

---

extensions/pipeline/releaseupgrade.go

Back port of https://github.com/rancher/shepherd/pull/68

[2.7] Adding helm repo URL in the config

---

clients/rancher/catalog/clusterrepo.go
extensions/pipeline/setup.go

Moved steveClient instantiation into the poll, to make sure the management.cattle.io.setting schema is properly found. This has been causing intermittent issues in recurring runs.

[v2.7] Fixed issue with post install steps from install Rancher

---

extensions/kubeapi/workloads/deployments/create.go

Backport https://github.com/rancher/shepherd/pull/84

[2.7] Add ability to provide replicas in the deployment spec

---

extensions/kubeapi/workloads/deployments/create.go

Backport https://github.com/rancher/shepherd/pull/84

[2.8] Add ability to provide replicas in the deployment spec

---

extensions/kubeapi/rbac/list.go
extensions/kubeapi/rbac/rbac.go
extensions/rbac/config.go
extensions/rbac/rbac.go
extensions/rbac/verify.go
extensions/settings/settings.go
extensions/settings/update.go

Back port https://github.com/rancher/shepherd/pull/16

[2.8] Adding extensions for rbac checks

---

extensions/kubeapi/rbac/list.go
extensions/rbac/config.go
extensions/rbac/rbac.go
extensions/rbac/verify.go
extensions/settings/settings.go
extensions/settings/update.go

Back port: https://github.com/rancher/shepherd/pull/16

[2.7] Adding extensions for rbac checks

---

extensions/kubeapi/rbac/rbac.go

Updating the right constant for localcluster

---

extensions/clusters/kubernetesversions/all.go

Forward port https://github.com/rancher/shepherd/pull/48
Issue: https://github.com/rancher/qa-tasks/issues/1122

Remove check for Rancher version in the kubernetesversions extension

---

extensions/clusters/kubernetesversions/all.go

Issue: https://github.com/rancher/qa-tasks/issues/1122
The [current implementation](https://github.com/rancher/rancher/blob/b57600cdc9b427f30f6c964ad46c535cce8f5c86/tests/framework/extensions/clusters/kubernetesversions/all.go#L228) assumes that the endpoints v1-rke2-release/releases and v1-k3s-release/releases return ALL available versions of RKE2/K3s (both compatible and incompatible). And, to filter out the compatible versions, we have code that checks if the Rancher version falls within the specified range of minChannelVersion to maxChannelVersion. I tested it with few Rancher versions and also confirmed with Max Ross that the endpoints return only the compatible versions. So, we can now remove this check. Extension 'kubernetesversions' is being updated to reflect this change.
Forward …

[2.7] Remove check for Rancher version in the kubernetesversions extension

---

extensions/machinepools/machinepools.go
extensions/nodes/node_status.go
extensions/provisioning/creates.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/sshkeys/downloadsshkeys.go

supports tests in: https://github.com/rancher/rancher/pull/43753

enable machinePool settings and nodeReplace ssh support

---

extensions/machinepools/machinepools.go
extensions/nodes/node_status.go
extensions/provisioning/creates.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/sshkeys/downloadsshkeys.go

port of https://github.com/rancher/shepherd/pull/14

[2.8] machinepool config

---

extensions/machinepools/machinepools.go
extensions/nodes/node_status.go
extensions/provisioning/creates.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/sshkeys/downloadsshkeys.go

https://github.com/rancher/shepherd/pull/14

[2.7]   enable machinePool settings and nodeReplace ssh support 

---

extensions/rke1/nodetemplates/aws/create.go
extensions/rke1/nodetemplates/aws_config.go
extensions/rke1/nodetemplates/azure/create.go
extensions/rke1/nodetemplates/azure_config.go
extensions/rke1/nodetemplates/harvester/create.go
extensions/rke1/nodetemplates/harvester_config.go
extensions/rke1/nodetemplates/linode/create.go
extensions/rke1/nodetemplates/linode_config.go
extensions/rke1/nodetemplates/nodetemplates.go
extensions/rke1/nodetemplates/vsphere/create.go
extensions/rke1/nodetemplates/vsphere_config.go

[2.8] Refactor `nodetemplates` extension

---

extensions/rke1/nodetemplates/aws/create.go
extensions/rke1/nodetemplates/aws_config.go
extensions/rke1/nodetemplates/azure/create.go
extensions/rke1/nodetemplates/azure_config.go
extensions/rke1/nodetemplates/harvester/create.go
extensions/rke1/nodetemplates/harvester_config.go
extensions/rke1/nodetemplates/linode/create.go
extensions/rke1/nodetemplates/linode_config.go
extensions/rke1/nodetemplates/nodetemplates.go
extensions/rke1/nodetemplates/vsphere/create.go
extensions/rke1/nodetemplates/vsphere_config.go

[2.7] Refactor `nodetemplates` extension

---

go.mod
go.sum

Bumps go version to 1.22 from 1.20

[Main] Bump main Branch to Go 1.22

---

go.mod
go.sum

Bumps go version to 1.21 from 1.20

[2.8] Bump release/v2.8 Branch to Go 1.21

---

extensions/rancherleader/rancherleader.go

https://github.com/rancher/qa-tasks/issues/1239
- Starting from Rancher version **2.8.3** and continuing into version 2.9.X, Rancher now uses `only Lease objects `for leader election. Before this change, it used a mix of ConfigMap and Lease objects. This implies that `lease object exists in 2.7, 2.8 and 2.9 releases`. So, "rancherleader" extension should be updated to use lease object instead of configmap.
- Update the "rancherleader" extension  to retrieve the rancher leader pod name using lease object.
```
https://Rancher_url/v1/coordination.k8s.io.leases?fieldSelector=metadata.name=cattle-controllers
```
**Backports:** Since `Lease` object is available in 2.7 and 2.8, we need backports for this
- 2.8: https://github.com/rancher/shepherd/pull/124
- 2.7: …

Update Rancher leader extension to use lease instead of configmap

---

extensions/defaults/stevetypes/stevetypes.go
extensions/etcdsnapshot/etcdsnapshot.go
extensions/provisioning/verify.go

All framework adjustments needed for the snapshot retention test as well as some updates to how we handle constants across the framework and in rancher tests. 
https://github.com/rancher/qa-tasks/issues/895

Snapshot retention test framework changes

---

extensions/defaults/stevetypes/stevetypes.go
extensions/etcdsnapshot/etcdsnapshot.go
extensions/provisioning/verify.go

Backport of https://github.com/rancher/shepherd/pull/75/files#diff-06c48b25669b482489241f1d6d4e4bd05d5d3e3551b33dc61b49675d9e15594b

[backport 2.8] Snapshot retention

---

extensions/defaults/stevetypes/stevetypes.go
extensions/etcdsnapshot/etcdsnapshot.go
extensions/provisioning/verify.go

Backport of [issue ](https://github.com/rancher/shepherd/pull/75/files#diff-06c48b25669b482489241f1d6d4e4bd05d5d3e3551b33dc61b49675d9e15594b)

[backport 2.7] Snapshot Retention test

---

.github/workflows/stale-prs.yml

Related Task - https://github.com/rancher/qa-tasks/issues/640
This PR has addressed these requirements:
- Report PRs with no reviews which are > 5 days old
- Report PRs with no updates which are > than 3 days old
- Report PRs which need reviews which are > than 3 days old
- PRs that have reviews but aren't merged (approved review) which are > than 3 days old

Adding workflow for identifying stale PRs

---

.github/scripts/build-packages.sh
.github/scripts/check-go-mod.sh
.github/workflows/verify-changes.yaml
.golangci.yaml
clients/k3d/config.go
clients/tfexec/tfexec.go
extensions/kubectl/template.go
extensions/rancherleader/rancherleader.go
pkg/clientbase/common.go
pkg/clientbase/ops.go
pkg/schemas/management.cattle.io/v3/schema.go

Adds a workflow that:
- Verifies mod file changes
- Builds packages inside `pkg`, `client`, and `extensions` dirs
- Uses `golangci-lint` to check linter issues
Triggers on:
- Every push (merges in this case)
- And when a pull request opens targeting `release/*` or `main`

[2.8] Add a Workflow That Verifies Changes

---

extensions/ingresses/ingresses.go

The charts test became flaky after recent HTTP call updates in external ingress helpers. The root cause; the body is drained as it's closed. But it's not read or stored anywhere. The same drained response body is used on the Rancher validation side, but it happens too late to read the body.
Added read body part to the function where the HTTP call happens. And now it returns the body as a string for further use of the same body.

[Main] Fix Response Body Reading in Ingresses Package

---

extensions/ingresses/ingresses.go

The charts test became flaky after recent HTTP call updates in external ingress helpers. The root cause; the body is drained as it's closed. But it's not read or stored anywhere. The same drained response body is used on the Rancher validation side, but it happens too late to read the body.
Added read body part to the function where the HTTP call happens. And now it returns the body as a string for further use of the same body.

[2.8] Fix Response Body Reading in Ingresses Package

---

extensions/ingresses/ingresses.go

The charts test became flaky after recent HTTP call updates in external ingress helpers. The root cause; the body is drained as it's closed. But it's not read or stored anywhere. The same drained response body is used on the Rancher validation side, but it happens too late to read the body.
Added read body part to the function where the HTTP call happens. And now it returns the body as a string for further use of the same body.

[2.7] Fix Response Body Reading in Ingresses Package

---

extensions/kubeapi/rbac/create.go
extensions/kubeapi/rbac/delete.go
extensions/kubeapi/rbac/update.go

Forward port of https://github.com/rancher/shepherd/pull/76

[2.9] Adding extensions for the global roles v2 webhook checks

---

extensions/kubeapi/namespaces/create.go

Currently, `Create Namespace` function in the kube api package accepts norman project as input. However, for automating test cases for Projects using the public API, I prefer not to reference the norman project or use functions that require norman or steve project input. So, to keep the create namespace function generic and not tied to any specific API (norman/steve/public), I'm modifying the function to accept clusterID and projectName as inputs instead of norman project.
**Backports:**
- 2.7: https://github.com/rancher/shepherd/pull/111
- 2.8: https://github.com/rancher/shepherd/pull/112

Modify CreateNamespace to accept clusterID and projectName as inputs instead of norman project

---

extensions/kubeapi/namespaces/create.go

Backport https://github.com/rancher/shepherd/pull/110

[2.8] Modify CreateNamespace to accept clusterID and projectName instead of norman project

---

extensions/kubeapi/namespaces/create.go

Backport https://github.com/rancher/shepherd/pull/110

[2.7] Modify CreateNamespace to accept clusterID and projectName instead of norman project

---

extensions/machinepools/machinepools.go
extensions/provisioning/creates.go
extensions/rke1/nodepools/nodepools.go

2.8 backport of https://github.com/rancher/shepherd/pull/134.

[v2.8] Fix flaky nodescaling test cases

---

extensions/machinepools/machinepools.go
extensions/provisioning/creates.go
extensions/rke1/nodepools/nodepools.go

2.7 backport of https://github.com/rancher/shepherd/pull/134.

[v2.7] Fix flaky nodescaling test cases

---

clients/rancher/catalog/clusterrepo.go
extensions/charts/vsphereoutoftree.go
extensions/cloudcredentials/vsphere/create.go
extensions/clusters/clusters.go
extensions/kubeapi/volumes/persistentvolumeclaims/persistentvolumeclaims.go
extensions/machinepools/vsphere_machine_config.go
extensions/provisioning/creates.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/rke1/nodetemplates/vsphere/create.go
extensions/rke1/nodetemplates/vsphere_config.go

port of https://github.com/rancher/shepherd/pull/103

[2.8] Enable automated install of vsphere cpi/csi

---

clients/rancher/catalog/clusterrepo.go
extensions/charts/vsphereoutoftree.go
extensions/cloudcredentials/vsphere/create.go
extensions/clusters/clusters.go
extensions/kubeapi/volumes/persistentvolumeclaims/persistentvolumeclaims.go
extensions/machinepools/vsphere_machine_config.go
extensions/provisioning/creates.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/rke1/nodetemplates/vsphere/create.go
extensions/rke1/nodetemplates/vsphere_config.go

port of https://github.com/rancher/shepherd/pull/103

[2.7] Enable automated install of vsphere cpi/csi

---

extensions/clusters/import.go

update import function to wait on service accounts to be available. Avoids flaky behavior

[2.9] update import function to wait on service accounts to be available. Avoids flaky behavior

---

extensions/clusters/import.go

port of https://github.com/rancher/shepherd/pull/159

[2.8] update imports

---

extensions/clusters/import.go

port of https://github.com/rancher/shepherd/pull/159

[2.7] update imports

---

extensions/clusters/clusters.go
extensions/machinepools/machinepools.go
extensions/steve/steve.go

backport of:
https://github.com/rancher/shepherd/pull/151

adds support for deleting init node

---

extensions/machinepools/azure_machine_config.go
extensions/rke1/nodetemplates/azure_config.go

port of https://github.com/rancher/shepherd/pull/178

[2.7] Fix Azure

---

extensions/machinepools/azure_machine_config.go
extensions/rke1/nodetemplates/azure_config.go

port of https://github.com/rancher/shepherd/pull/178

[2.8] Fix Azure

---

pkg/wrangler/context.go

Issue: https://github.com/rancher/shepherd/issues/171

Wrangler context to interact with downstream clusters

---

extensions/clusters/clusters.go
extensions/machinepools/machinepools.go

Backport of https://github.com/rancher/shepherd/pull/181.

[v2.7] Fix delete init node for RKE2 clusters

---

extensions/provisioning/creates.go

Backport to https://github.com/rancher/shepherd/pull/189.

[v2.7] Fix internal IP annotation for custom cluster deletion

---

extensions/provisioning/creates.go

Backport to https://github.com/rancher/shepherd/pull/189.

[v2.8] Fix internal IP annotation for custom cluster deletion

---

extensions/rke1/nodetemplates/aws/create.go
extensions/rke1/nodetemplates/aws_config.go
extensions/rke1/nodetemplates/azure/create.go
extensions/rke1/nodetemplates/azure_config.go
extensions/rke1/nodetemplates/harvester/create.go
extensions/rke1/nodetemplates/harvester_config.go
extensions/rke1/nodetemplates/linode/create.go
extensions/rke1/nodetemplates/linode_config.go
extensions/rke1/nodetemplates/vsphere/create.go

Backport of https://github.com/rancher/shepherd/pull/194.

[v2.7] Fix RKE1 nodetemplates to include cloud credentials

---

extensions/auth/auth.go
extensions/auth/openldap/config.go
extensions/auth/openldap/openldap.go

Issue: https://github.com/rancher/qa-tasks/issues/1283
Adds:
- Open LDAP and its enable/disable method functions.
- Auth and its constructor.

[Main] Add Open LDAP and Auth Extensions

---

extensions/auth/auth.go
extensions/auth/openldap/config.go
extensions/auth/openldap/openldap.go

Issue: https://github.com/rancher/qa-tasks/issues/1283
Adds:
- Open LDAP and its enable/disable method functions.
- Auth and its constructor.

[2.8] Add Open LDAP and Auth Extensions 

---

extensions/auth/auth.go
extensions/auth/openldap/config.go
extensions/auth/openldap/openldap.go

Issue: https://github.com/rancher/qa-tasks/issues/1283
Adds:
- Open LDAP and its enable/disable method functions.
- Auth and its constructor.

[2.7] Add Open LDAP and Auth Extensions

---

extensions/charts/rke2template.go
extensions/defaults/stevetypes/stevetypes.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/steve/steve.go
extensions/wait/wait.go

Release testing PR for rke2 templates.
Issue: https://github.com/rancher/qa-tasks/issues/542

RKE2 template test

---

extensions/charts/rke2template.go
extensions/defaults/stevetypes/stevetypes.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/steve/steve.go
extensions/wait/wait.go

Backport of https://github.com/rancher/shepherd/pull/197

[backport2.7] RKE2-templates

---

extensions/charts/rke2template.go
extensions/defaults/stevetypes/stevetypes.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/steve/steve.go
extensions/wait/wait.go

backport of https://github.com/rancher/shepherd/pull/197

[Backport 2.8] RKE2 templates

---

extensions/charts/cisbenchmark.go
extensions/charts/config.go
extensions/charts/payloads.go
extensions/charts/ranchergatekeeper.go
extensions/charts/rancheristio.go
extensions/charts/ranchermonitoring.go
extensions/charts/verify.go
extensions/charts/vsphereoutoftree.go
extensions/rke1/nodetemplates/vsphere/create.go
extensions/rke1/nodetemplates/vsphere_config.go

port of: https://github.com/rancher/shepherd/pull/211

adding support to upgrade out-of-tree charts for rke1 vsphere

---

extensions/kubeapi/projects/projects.go

https://github.com/rancher/qa-tasks/issues/1394
Adding a template for Project that can be used in tests using the project public API
2.8 Backport PR: https://github.com/rancher/shepherd/pull/221

Template for project

---

extensions/kubeapi/projects/projects.go

Backport: https://github.com/rancher/shepherd/pull/220

[2.8] Template for project

---

extensions/kubeapi/configmaps/configmaps.go

This code adds support for creating configmaps for use in this test: https://github.com/rancher/rancher/pull/44898

[Main] Configmap Template for Creating Configmaps

---

extensions/kubeapi/configmaps/configmaps.go

This code adds support for creating configmaps for use in this test: https://github.com/rancher/rancher/pull/43599

[2.8] Configmap Template for Creating Configmaps

---

extensions/kubeapi/configmaps/configmaps.go

This code adds support for creating configmaps for use in this test: https://github.com/rancher/rancher/pull/44897

[2.7] Configmap Template for Creating Configmaps

---

clients/rancher/catalog/clusterrepo.go
clients/rancher/v1/client.go

Also a panic fix for the clusterrepo client.

Added fix for getting the schema of a non admin user. 

---

clients/rancher/catalog/clusterrepo.go
clients/rancher/v1/client.go

Also a panic fix for the clusterrepo client.

[v2.8] Added fix for getting the schema of a non admin user. 

---

clients/rancher/catalog/clusterrepo.go
clients/rancher/v1/client.go

Also a panic fix for the clusterrepo client.

[v2.7] Added fix for getting the schema of a non admin user. 

---

pkg/wrangler/context.go

Backport https://github.com/rancher/shepherd/pull/243

[2.8] Refactor context to store session for downstream context creation

---

extensions/clusters/clusters.go
extensions/upgradeinput/config.go
extensions/upgradeinput/load.go

Backport of https://github.com/rancher/shepherd/pull/231.

[v2.8] Update LoadUpgradeKubernetesConfig for upgrade refactor

---

pkg/api/steve/catalog/types/rest.go

Related PR: https://github.com/rancher/rancher/pull/46347
- Adds new fields to the catalog client's new REST types

Update catalog Rest types for Catalog Client

---

clients/rancher/client.go

https://github.com/rancher/shepherd/pull/250

[2.9] Add the user field to rancher clients

---

clients/rancher/client.go

https://github.com/rancher/shepherd/pull/250

[2.7] Add the user field to rancher clients

---

clients/rancher/client.go

https://github.com/rancher/shepherd/pull/250

[2.8] Add the user field to rancher clients

---

.github/workflows/stale-prs.yml

https://github.com/rancher/qa-tasks/issues/1259
- Excludes draft PRs after obtaining reviews.
- Changed the sha of the actions/checkout and actions/github-scripts to the latest release as there were some warnings in the console logs while the action runs.
- Added bold formatting to the report statements.
Report will be sent on slack.

Updating the workflow to skip draft PRs

---

CODEOWNERS

Cherry picks code owners from the main

[2.8] Cherry Pick Codeowners

---

CODEOWNERS

Cherry picks code owners from the main

[2.7] Cherry Pick Codeowners

---

CODEOWNERS

Cherry picks code owners from the main

[2.9] Cherry Pick Codeowners

---

extensions/kubectl/command.go

Changed kubectl Command function to use a ProxyDownstream steve cliente by cluster

<2.9> Fixed pod logs streaming error

---

extensions/kubectl/command.go

Changed kubectl Command function to use a ProxyDownstream steve cliente by cluster

<2.7> Fixed pod logs streaming error

---

extensions/kubectl/command.go

Changed kubectl Command function to use a ProxyDownstream steve cliente by cluster

<v2.8> Fixed pod logs streaming error

---

extensions/workloads/template.go

Backport of https://github.com/rancher/shepherd/pull/249.

[v2.9] Add Windows support for scaling nodepools

---

extensions/workloads/template.go

Backport of https://github.com/rancher/shepherd/pull/249.

[v2.8] Add Windows support for scaling nodepools

---

extensions/workloads/template.go

Backport of https://github.com/rancher/shepherd/pull/249.

[v2.7] Add Windows support for scaling nodepools

---

extensions/cloudcredentials/aws/create.go
extensions/cloudcredentials/azure/create.go
extensions/cloudcredentials/cloudcredentials.go
extensions/cloudcredentials/digitalocean/create.go
extensions/cloudcredentials/google/create.go
extensions/cloudcredentials/harvester/create.go
extensions/cloudcredentials/linode/create.go
extensions/cloudcredentials/vsphere/create.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/providers/providers.go

Update cloud credentials functions for every provider.

Credentials update

---

extensions/clusters/kubernetesversions/all.go

[2.8] updating sortReleases key=minor version instead of rancherMinorversion

---

.gitignore
extensions/clusters/aks/aks_cluster_config.go
extensions/clusters/eks/eks_cluster_config.go
extensions/clusters/gke/gke_cluster_config.go

Fixes: #274 
Changes introduced with the PR:
1. Update GKE ClusterConfig and HostedClusterConfig with new fields from management.GKEClusterConfigSpec
2. Update AKS ClusterConfig and HostedClusterConfig with new fields from management.AKSClusterConfigSpec
3. Update EKS ClusterConfig and HostedClusterConfig with new fields from management.EKSClusterConfigSpec
4. Add `.idea` to .gitignore.

[main] Update ClusterConfig with management.*ClusterConfigSpec

---

.gitignore
extensions/clusters/aks/aks_cluster_config.go
extensions/clusters/eks/eks_cluster_config.go
extensions/clusters/gke/gke_cluster_config.go

Fixes: #274 
Changes introduced with the PR:
1. Update GKE ClusterConfig and HostedClusterConfig with new fields from management.GKEClusterConfigSpec
2. Update AKS ClusterConfig and HostedClusterConfig with new fields from management.AKSClusterConfigSpec
3. Update EKS ClusterConfig and HostedClusterConfig with new fields from management.EKSClusterConfigSpec
4. Add `.idea` to .gitignore.

[2.9] Update ClusterConfig with management.*ClusterConfigSpec

---

.github/pull_request_template.md
README.md

- Adds PR Template
- Updates README
- Moves concepts to the Wiki

[Main] Add PR template and update README

---

.github/pull_request_template.md
README.md

- Adds PR Template
- Updates README
- Moves concepts to the Wiki

[2.9] Add PR template and update README

---

.github/pull_request_template.md
README.md

- Adds PR Template
- Updates README
- Moves concepts to the Wiki

[2.8] Add PR template and update README

---

.github/pull_request_template.md
README.md

- Adds PR Template
- Updates README
- Moves concepts to the Wiki

[2.7] Add PR template and update README

---

extensions/fleet/fleet.go

supports: https://github.com/rancher/qa-tasks/issues/1514

[Fleet Integration] adding support for fleet gitRepo creation. Mimics clusters.go

---

extensions/fleet/fleet.go

port of https://github.com/rancher/shepherd/pull/286

[2.8] adding support for fleet gitRepo creation. Mimics clusters.go

---

extensions/fleet/fleet.go

port of https://github.com/rancher/shepherd/pull/286

[2.7] adding support for fleet gitRepo creation. Mimics clusters.go

---

extensions/clusters/eks/eks_cluster_config.go

v2.8 backport of https://github.com/rancher/shepherd/pull/297

[v2.8] Add support for setting k8s version in EKS NodeGroup

---

extensions/clusters/eks/eks_cluster_config.go

[v2.9] Add support for setting k8s version in EKS NodeGroup

---

extensions/clusters/eks/eks_cluster_config.go

[v2.7] Add support for setting k8s version in EKS NodeGroup

---

extensions/users/users.go

With the 1.31 bumps,  `AddProjectMember` fails in different test cases consistently due to a time-out error while waiting for the `checkFunc`.
Include the project's namespace to populate watch events that are affected by the 1.31 dependency bumps. 
TBD -- So far tested on:
- Sample image with 1.31 bumps
- Latest 2.9 image

Fix(extensions/users): Update AddProjectMember Watcher to Include Namespace of the Project

---

clients/corral/config.go
clients/corral/corral.go

port of https://github.com/rancher/shepherd/pull/225

[main] update airgap create functions to support multi-pool configurations

---

clients/corral/config.go
clients/corral/corral.go

port of https://github.com/rancher/shepherd/pull/225

[2.8] update airgap create functions to support multi-pool configurations

---

clients/corral/config.go
clients/corral/corral.go

port of https://github.com/rancher/shepherd/pull/225

[2.7] update airgap create functions to support multi-pool configurations

---

extensions/clusters/clusters.go
extensions/etcdsnapshot/etcdsnapshot.go

port of https://github.com/rancher/shepherd/pull/304

[2.9] improve snapshot creation and validation

---

extensions/clusters/clusters.go
extensions/etcdsnapshot/etcdsnapshot.go

https://github.com/rancher/qa-tasks/issues/1525
snapshots weren't modular enough to directly move to actions, and there was some flaky behavior when using the underlying functions when testing. 
* created a new func in clusters.go to wait on snapshots to finish being taken based on observed behavior when taking snapshots
* improved return of etcd snapshot create function calls to only return a list of snapshots created after the snapshot was initiated
* since rancher doesn't explicitly do this for you, I added logic to return the created snapshots vs. all snapshots (default rancher behavior) to improve validations later + match behavior of other 'create' functions in shepherd
tested on rke1 + rke2 snapshot and restores for most complex automated use case (snapshot, upgrade, restore) …

improve snapshot creation and validation

---

go.mod
go.sum

The second part of https://github.com/rancher/shepherd/pull/321
Remove fork version of the schema and use the latest pkg/apis

[Main] Remove replace, bump pkg/apis to the latest

---

pkg/config/config.go
pkg/config/operations/operations.go
pkg/config/operations/permutations/example_test.go
pkg/config/operations/permutations/permutations.go

Backport of https://github.com/rancher/shepherd/pull/279

[2.7] Generic Permutations

---

go.mod
go.sum

Related to https://github.com/rancher/shepherd/pull/334

Remove temporary fork of rancher/pkg/apis

---

clients/harvester/client.go
clients/harvester/config.go

port of https://github.com/rancher/shepherd/pull/351

[v2.10] harvester client

---

clients/harvester/client.go
clients/harvester/config.go

port of https://github.com/rancher/shepherd/pull/351

[v2.9] harvester client

---

clients/harvester/client.go
clients/harvester/config.go

port of https://github.com/rancher/shepherd/pull/351

[v2.8] harvester client

---

clients/rkecli/state.go

https://github.com/rancher/qa-tasks/issues/1295
RKE1 cluster upgrade fails as the state file stays in a secret instead of a config map. This has been previously in a configmap.
Updates the state file used in the code from a config map to a state map.
Jenkins log
_TODO_

Updating the state file for rke1 clusters

---

clients/rkecli/state.go

Backport of https://github.com/rancher/shepherd/pull/356

[2.10] Update rke state file

---

pkg/config/operations/permutations/permutations.go

Found a bug with generic permutations that caused relationships to not be applied correctly when multiple relationships were present.
Note: since this is limited to relationships, the main use case of generic permutations should be unaffected.
Fix relationships to appropriately apply when multiple relationships are present and move the logic into its own function for clarity.
Tested locally as part of the os check development.

Fix generic permutation relationships.

---

pkg/config/operations/permutations/permutations.go

Backport of: https://github.com/rancher/shepherd/pull/360

[Backport 2.10] Fix generic permutation relationships.

---

pkg/config/operations/permutations/permutations.go

Backport of: https://github.com/rancher/shepherd/pull/360

[Backport 2.9] Fix generic permutation relationships.

---

pkg/config/operations/permutations/permutations.go

Backport of: https://github.com/rancher/shepherd/pull/360

[Backport 2.8] Fix generic permutation relationships.

---

clients/k3d/k3d.go
extensions/clusters/kubernetesversions/all.go
extensions/clusters/kubernetesversions/available.go

- Fix a few missing error checks
- Fix the value of eksVersionsFileURL and consequently fix ListEKSAllVersions.
Backport of #368

[2.9] Add missing error check and fix ListEKSAllVersions

---

CODEOWNERS

… for now to unblock raft PRs.
_TODO_

[main] Added igomez back to code owners,

---

CODEOWNERS

… for now to unblock raft PRs.
_TODO_

[2.10] Added igomez back to code owners

---

CODEOWNERS

… for now to unblock raft PRs.
_TODO_

[2.9] Added igomez back to code owners

---

CODEOWNERS

… for now to unblock raft PRs.
_TODO_

[2.8] Added igomez back to code owners

---

clients/rancher/client.go

[BP 2.10] Enable creating a rancher client by directly passing a *Config

---

clients/rancher/client.go

[BP 2.9] enable creating a rancher client by directly passing a *Config

---

clients/rancher/client.go

[BP 2.8] Enable creating a rancher client by directly passing a *Config

---

clients/ec2/client.go
extensions/cloudcredentials/aws/create.go
extensions/cloudcredentials/aws_config.go
extensions/cloudcredentials/azure/create.go
extensions/cloudcredentials/digitalocean/create.go
extensions/cloudcredentials/google/create.go
extensions/cloudcredentials/harvester/create.go
extensions/cloudcredentials/linode/create.go
extensions/cloudcredentials/vsphere/create.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/stevestates/stevestates.go
extensions/defaults/stevetypes/stevetypes.go
extensions/steve/steve.go

Backport of: https://github.com/rancher/shepherd/pull/373

[backport 2.10] OS check helpers 

---

clients/ec2/client.go
extensions/cloudcredentials/aws/create.go
extensions/cloudcredentials/aws_config.go
extensions/cloudcredentials/azure/create.go
extensions/cloudcredentials/digitalocean/create.go
extensions/cloudcredentials/google/create.go
extensions/cloudcredentials/harvester/create.go
extensions/cloudcredentials/linode/create.go
extensions/cloudcredentials/vsphere/create.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/stevestates/stevestates.go
extensions/defaults/stevetypes/stevetypes.go
extensions/steve/steve.go

Backport of: https://github.com/rancher/shepherd/pull/373

[Backport 2.9] OS check helpers

---

extensions/harvester/sakubeconfig.go

port of https://github.com/rancher/shepherd/pull/384

[2.8] add sakubeconfig harvester

---

extensions/harvester/sakubeconfig.go

port of https://github.com/rancher/shepherd/pull/384

[2.9] add sakubeconfig harvester

---

clients/harvester/client.go
clients/rancher/client.go
extensions/workloads/pods/pod_status.go

[2.10] Add ForConfig functions for functions in Rancher and Harvester Clients

---

extensions/users/users.go

CI keeps failing after shepherd version bump in rancher/rancher. This line seems to be the culprit.

fix broken function, removing if statement

---

extensions/sshkeys/downloadsshkeys.go

Rancher PR: https://github.com/rancher/tests/pull/195
The current implementation of various SSH functions utilizes the default SSH username (ubuntu) in rancher, which causes any other OS type to fail.
Fix:
* Reworked the sshKeys extension to pull username, IP and sshKey from the v1/cluster.x-k8s.io.machines api endpoint

Update SSH functions to work with a non-default ssh user

---

extensions/sshkeys/downloadsshkeys.go

https://github.com/rancher/shepherd/pull/413

[Backport 2.11] Update SSH functions to work with a non-default ssh user

---

extensions/sshkeys/downloadsshkeys.go

https://github.com/rancher/shepherd/pull/413

[Backport 2.12] Update SSH functions to work with a non-default ssh user

---

extensions/sshkeys/downloadsshkeys.go

https://github.com/rancher/shepherd/pull/413

[Backport 2.10] Update SSH functions to work with a non-default ssh user

---

extensions/clusters/clusters.go
extensions/clusters/kubernetesversions/default.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/stevetypes/stevetypes.go
extensions/ingresses/ingresses.go
extensions/ingresses/wait.go
extensions/nodes/node_status.go
extensions/steve/steve.go

Issue: https://github.com/rancher/shepherd/pull/419

[backport 2.11] logging rework

---

extensions/clusters/clusters.go
extensions/clusters/kubernetesversions/default.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/stevetypes/stevetypes.go
extensions/ingresses/ingresses.go
extensions/ingresses/wait.go
extensions/nodes/node_status.go
extensions/steve/steve.go

Issue: https://github.com/rancher/shepherd/pull/419

[backport 2.10]

---

extensions/workloads/pods/pod_status.go

Update logging for pods_status

---

extensions/workloads/pods/pod_status.go

Backport: https://github.com/rancher/shepherd/pull/423

[Backport 2.10] fix pod status

---

.github/workflows/create-rancher-pr.yml

Main test gha
