extensions/clusters/clusters.go
extensions/rke1/componentchecks/etcdversion.go

For RKE1 custom cluster provisioning, we perform a check for the etcd etcdctl version in each etcd node. This test specifically was created when we are doing release checks. This is not working due to an issue seen in the function `CheckETCDVersion`.
Fixed the issue in `CheckETCDVersion` function.
Manually ran the RKE1 custom cluster test and this was successful.
Jenkins jobs will be provided offline to reviewers.

[v2.8] Fix etcd version not displaying version in CheckETCDVersion

---

extensions/clusters/clusters.go
extensions/rke1/componentchecks/etcdversion.go

For RKE1 custom cluster provisioning, we perform a check for the etcd etcdctl version in each etcd node. This test specifically was created when we are doing release checks. This is not working due to an issue seen in the function `CheckETCDVersion`.
Fixed the issue in `CheckETCDVersion` function.
Manually ran the RKE1 custom cluster test and this was successful.
Jenkins jobs will be provided offline to reviewers.

[v2.7] Fix etcd version not displaying version in CheckETCDVersion

---

extensions/clusters/bundledclusters/update.go

Adds `rkecli` import in the bundledclusters package.

Fix rkecli client import in bundledclusters

---

extensions/clusters/bundledclusters/update.go

Adds `rkecli` import in the bundledclusters package.

[2.8] Fix rkecli client import in bundledclusters

---

extensions/clusters/bundledclusters/update.go

Adds `rkecli` import in the bundledclusters package.

[2.7] Fix rkecli client import in bundledclusters

---

extensions/rke1/componentchecks/etcdversion.go

When running the RKE1 custom cluster provisioning tests, there is a specific check for the `etcdctl` version. When running the DynamicInput tests, this passes. For the static TDD tests, they fail.
Troubleshooting, it is because the etcd node has the private IP address in the external AND internal IP address for only the static tests; the dynamic tests do not share this problem.
To fix this/polish up the check further, removing the additional if condition for checking the externalIP; so long as the `etcdRole` is true, run the docker exec command. This will occur only on the first etcd node, then it will break the check.

[v2.9] Fix etcdctl version check for static and dynamic tests

---

extensions/rke1/componentchecks/etcdversion.go

When running the RKE1 custom cluster provisioning tests, there is a specific check for the `etcdctl` version. When running the DynamicInput tests, this passes. For the static TDD tests, they fail.
Troubleshooting, it is because the etcd node has the private IP address in the external AND internal IP address for only the static tests; the dynamic tests do not share this problem.
To fix this/polish up the check further, removing the additional if condition for checking the externalIP; so long as the `etcdRole` is true, run the docker exec command. This will occur only on the first etcd node, then it will break the check.

[v2.8] Fix etcdctl version check for static and dynamic tests

---

extensions/pipeline/releaseupgrade.go
extensions/upgradeinput/config.go
extensions/upgradeinput/load.go

Issue: https://github.com/rancher/qa-tasks/issues/1096
Adds `upgradeinput` package with upgrade tests configuration and its load functions.

[Main] Move Upgrade Test Configurations and Load Functions

---

extensions/pipeline/releaseupgrade.go
extensions/upgradeinput/config.go
extensions/upgradeinput/load.go

Adds `upgradeinput` package with upgrade tests configuration and its load functions.

[2.8] Move Upgrade Test Configurations and Load Functions

---

extensions/etcdsnapshot/config.go
extensions/etcdsnapshot/etcdsnapshot.go
extensions/nodes/node_status.go

As part of ongoing additional etcd snapshot coverage, one test case we manually check is rotating nodes after creating an etcd shapshot. This quickly becomes a pain manually, so it should be automated.
Adds support for rotating worker nodes after creating an etcd snapshot. Additionally, gives needed stability in flakiness found during release testing in the snapshot tests.
- K3S (3 etcd, 2 cp, 3 worker) DynamcInput with upgrade strategy
- K3S (1 etcd, 1 cp, 1 worker) DynamcInput with upgrade strategy
- RKE1 (3 etcd, 2 cp, 3 worker) DynamcInput with upgrade strategy
Jenkins jobs will be provided offline to the reviewers.

[v2.9] Add support for rotating worker nodes after creating an etcd snapshot

---

extensions/etcdsnapshot/config.go
extensions/etcdsnapshot/etcdsnapshot.go
extensions/nodes/node_status.go

v2.8 backport of https://github.com/rancher/shepherd/pull/59

[v2.8] Add support for rotating worker nodes after creating an etcd snapshot

---

extensions/etcdsnapshot/config.go
extensions/etcdsnapshot/etcdsnapshot.go
extensions/nodes/node_status.go

v2.7 backport of https://github.com/rancher/shepherd/pull/59

[v2.7] Add support for rotating worker nodes after creating an etcd snapshot

---

clients/rancher/config.go
clients/rkecli/config.go
clients/rkecli/state.go
extensions/pipeline/releaseupgrade.go

- Updates Rancher client configuration to have JSON tags. 
- Add two different SSH options to RKECLI client and its configuration:
1. SSHKey: mainly for corral and CI usage
2. SSHPath: mainly for legacy tests and local usage
- Update release upgrade-related glue codes with local options and simplify the field names.

[2.8] Update Rancher Client Configurations and RKE Client to Have Different SSH Configuration Options

---

clients/rancher/config.go
clients/rkecli/config.go
clients/rkecli/state.go
extensions/pipeline/releaseupgrade.go

- Updates Rancher client configuration to have JSON tags. 
- Add two different SSH options to RKECLI client and its configuration:
1. SSHKey: mainly for corral and CI usage
2. SSHPath: mainly for legacy tests and local usage
- Update release upgrade-related glue codes with local options and simplify the field names.

[2.7] Update Rancher Client Configurations and RKE Client to Have Different SSH Configuration Options

---

extensions/pipeline/setup.go

Moved steveClient instantiation into the poll, to make sure the management.cattle.io.setting schema is properly found. This has been causing intermittent issues in recurring runs.

Fixed issue with post install steps from install Rancher

---

extensions/pipeline/setup.go

Moved steveClient instantiation into the poll, to make sure the management.cattle.io.setting schema is properly found. This has been causing intermittent issues in recurring runs.

[v2.8] Fixed issue with post install steps from install Rancher

---

extensions/kubeapi/workloads/deployments/create.go

Currently, we cannot provide the replica count when creating a deployment using kube api. As part of this PR, I'm modifying '`CreateDeployment`' function under kubeapi to accept number of replicas. 
Note: 
- This function is not being used by any existing tests so modifying it won't break any tests.
- This PR requires a back port in 2.7 and 2.8.
- Backport 2.7: https://github.com/rancher/shepherd/pull/85
- Backport 2.8: https://github.com/rancher/shepherd/pull/86

Add ability to provide replicas in the deployment spec

---

extensions/kubeapi/rbac/list.go
extensions/kubeapi/rbac/rbac.go
extensions/rbac/config.go
extensions/rbac/rbac.go
extensions/rbac/verify.go
extensions/settings/settings.go
extensions/settings/update.go

Extension in this PR are to enhance the extensions for rbac checks. Once approved, this needs a back port in 2.7 and 2.8 branches as well.
Rancher PR that uses the extensions from this PR: https://github.com/rancher/rancher/pull/43661

Adding extensions for rbac checks

---

extensions/rke1/nodetemplates/aws/create.go
extensions/rke1/nodetemplates/aws_config.go
extensions/rke1/nodetemplates/azure/create.go
extensions/rke1/nodetemplates/azure_config.go
extensions/rke1/nodetemplates/harvester/create.go
extensions/rke1/nodetemplates/harvester_config.go
extensions/rke1/nodetemplates/linode/create.go
extensions/rke1/nodetemplates/linode_config.go
extensions/rke1/nodetemplates/nodetemplates.go
extensions/rke1/nodetemplates/vsphere/create.go
extensions/rke1/nodetemplates/vsphere_config.go

It is currently not possible to set top-level NodeTemplate fields via configfile. The current implementation assumes defaults and is difficult to modify on the fly. Provider-specific node template configuration file keys do not match the top-level NodeTemplate struct keys.
- Enable setting top-level nodetemplate fields
- Enable setting entire nodetemplate via config file
- **BREAKING** Update provider-specific configfile keys to match their top-level NodeTemplate key
- Add custom merge function for NodeTemplate
- Can still set provider-specific nodetemplate configuration separately via config file
- Should maintain backwards-compatibility if the top-level NodeTemplate configuration key is not present in the config file
- Specification of the updated provider-specific node template …

Refactor nodetemplates extension

---

extensions/rke1/nodetemplates/aws/create.go
extensions/rke1/nodetemplates/azure/create.go
extensions/rke1/nodetemplates/harvester/create.go
extensions/rke1/nodetemplates/linode/create.go
extensions/rke1/nodetemplates/nodetemplates.go
extensions/rke1/nodetemplates/vsphere/create.go
go.mod
go.sum

Remove custom MergeOverride() function due to incompatibility with golang v1.21. Replace with mergo.Merge() with override flag

[2.7] Update RKE1 nodetemplates v2.7

---

.github/scripts/build-packages.sh
.github/scripts/check-go-mod.sh
.github/workflows/verify-changes.yaml
.golangci.yaml
clients/k3d/config.go
clients/tfexec/tfexec.go
extensions/kubectl/template.go
extensions/rancherleader/rancherleader.go
pkg/clientbase/common.go
pkg/clientbase/ops.go
pkg/schemas/management.cattle.io/v3/schema.go

Adds a workflow that:
- Verifies mod file changes
- Builds packages inside `pkg`, `client`, and `extensions` dirs
- Uses `golangci-lint` to check linter issues
Triggers on:
- Every push (merges in this case)
- And when a pull request opens targeting `release/*` or `main`

[Main] Add a Workflow That Verifies Changes

---

.github/scripts/build-packages.sh
.github/scripts/check-go-mod.sh
.github/workflows/verify-changes.yaml
.golangci.yaml
clients/k3d/config.go
clients/tfexec/tfexec.go
extensions/kubectl/template.go
extensions/rancherleader/rancherleader.go
extensions/rke1/nodetemplates/nodetemplates.go
pkg/clientbase/common.go
pkg/clientbase/ops.go
pkg/schemas/management.cattle.io/v3/schema.go

Adds a workflow that:
- Verifies mod file changes
- Builds packages inside `pkg`, `client`, and `extensions` dirs
- Uses `golangci-lint` to check linter issues
Triggers on:
- Every push (merges in this case)
- And when a pull request opens targeting `release/*` or `main`

[2.7] Add a Workflow That Verifies Changes

---

extensions/kubeapi/rbac/create.go
extensions/kubeapi/rbac/delete.go
extensions/kubeapi/rbac/update.go

Depends on https://github.com/rancher/rancher/pull/43363
For the global roles v2 webhook checks, we need a few extensions:
1. Create Role templates
2. CreateClusterRoleTemplateBinding
3. DeleteClusterRoletemplate
4. UpdateRoleTemplate
5. UpdateClusterRoleTemplateBindings
All of these extensions are using dynamic clients[kubernetes API], so we only need to back port the fix in 2.8. Public API was introduces in 2.8, so these extensions need not be in 2.7.

[2.8] Adding extension for the global roles v2 webhook checks

---

extensions/charts/awsoutoftree.go
extensions/charts/verify.go
extensions/clusters/clusters.go
extensions/kubectl/template.go

note; sometimes, the kubectl command is still flaky. This was pulled from this [PR](https://github.com/rancher/shepherd/pull/17) since it hasn't merged yet, which is an improvement from what's currently in but not 100% 
example of the bug from kubectl, hit intermittently
```
an error on the server ("unable to create impersonator account: error setting up impersonation for user user-kcbbw: impersonation: error ensuring secret for service account cattle-impersonation-user-kcbbw: error ensuring secret for service account [cattle-impersonation-system:cattle-impersonation-user-kcbbw]: timed out waiting for the condition") has prevented the request from succeeding
```
the other problem I'll see is this, followed by a timeout
```
child pods are preserved by default when jobs are deleted; set …
```

make out-of-tree helpers public for additional testing during upgrades

---

extensions/charts/awsoutoftree.go
extensions/charts/verify.go
extensions/clusters/clusters.go
extensions/kubectl/template.go

port of https://github.com/rancher/shepherd/pull/74

[2.8] make out-of-tree helpers public for additional testing during upgrades

---

extensions/charts/awsoutoftree.go
extensions/charts/verify.go
extensions/clusters/clusters.go
extensions/kubectl/template.go

port of https://github.com/rancher/shepherd/pull/74

[2.7]  make out-of-tree helpers public for additional testing during upgrades

---

extensions/machinepools/machinepools.go
extensions/provisioning/creates.go
extensions/rke1/nodepools/nodepools.go

During release testing, there was quite a bit of flakiness seen with the nodescaling for both node driver and custom clusters; specifically, with RKE2/K3s. This PR is the shepherd PR to address flakiness shown. The complimentary rancher/rancher PR contains additional fixes.

[v2.9] Fix flaky nodescaling test cases

---

clients/rancher/catalog/clusterrepo.go
extensions/charts/vsphereoutoftree.go
extensions/cloudcredentials/vsphere/create.go
extensions/clusters/clusters.go
extensions/kubeapi/volumes/persistentvolumeclaims/persistentvolumeclaims.go
extensions/machinepools/vsphere_machine_config.go
extensions/provisioning/creates.go
extensions/provisioning/verify.go
extensions/provisioninginput/config.go
extensions/rke1/nodetemplates/vsphere/create.go
extensions/rke1/nodetemplates/vsphere_config.go

https://github.com/rancher/rancher/pull/44787
enables the following option in the config:
```
provisioningInput:
cloudProvider: "rancher-vsphere"
```
which will allow the user to use vsphere with either rke1 or rke2. 
Other Improvements:
* added an option to populate default values for a given chart
* formatting updates
* added `DatastoreUrl` for vsphere rke2 and rke1

Enable automated install of vsphere cpi/csi

---

clients/rancher/client.go
clients/rancher/config.go
clients/ranchercli/client.go
extensions/cli/cli.go

As part of broader efforts to fix flaky tests, it was discussed to shift away from the flaky Python tests for the Rancher CLI and transition them over to Go. As such, all of the tests minus apps have been translated. This is because `rancher apps` has known failures in the Rancher CLI.

[v2.9] Convert flaky Python CLI tests to Go

---

clients/rancher/client.go
clients/rancher/config.go
clients/ranchercli/client.go
extensions/cli/cli.go

Backport of https://github.com/rancher/shepherd/pull/145.

[v2.7] Convert flaky Python CLI tests to the Go

---

extensions/charts/awsoutoftree.go
extensions/charts/charts.go
extensions/charts/rancheralerting.go
extensions/charts/ranchergatekeeper.go
extensions/charts/rancheristio.go
extensions/charts/rancherlogging.go
extensions/charts/ranchermonitoring.go
extensions/charts/vsphereoutoftree.go

Chart installations only support RKE1 clusters. Ultimately for chart installations on the Airgap environment, the chart tests need to be enhanced to include an Alerting Driver chart too.
Add Monitoring and Logging charts' payload mappers. Update chart installs option struct to have cluster meta - which is used within these mappers. Add Alerting Driver installation function that supports RKE1/RKE2/K3s installations.

[2.8] Add Alerting Drivers Chart Installation, Update Monitoring and Logging Charts to Support Different Provider Installations

---

extensions/charts/awsoutoftree.go
extensions/charts/charts.go
extensions/charts/rancheralerting.go
extensions/charts/ranchergatekeeper.go
extensions/charts/rancheristio.go
extensions/charts/rancherlogging.go
extensions/charts/ranchermonitoring.go
extensions/charts/vsphereoutoftree.go

Chart installations only support RKE1 clusters. Ultimately for chart installations on the Airgap environment, the chart tests need to be enhanced to include an Alerting Driver chart too.
Add Monitoring and Logging charts' payload mappers. Update chart installs option struct to have cluster meta - which is used within these mappers. Add Alerting Driver installation function that supports RKE1/RKE2/K3s installations.

[2.7] Add Alerting Drivers Chart Installation, Update Monitoring and Logging Charts to Support Different Provider Installations

---

extensions/machinepools/azure_machine_config.go
extensions/rke1/nodetemplates/azure_config.go

azure was missing fields for location (machinepools) and NSG (nodetemplates) - adding this to the config

[2.9] add updated fields to azure machinepool + nodetemplate

---

extensions/clusters/clusters.go
extensions/machinepools/machinepools.go

The delete init node test is working only for K3s clusters and not RKE2 clusters. This is because there is no current way in which the appropriate secret is getting grabbed.
To address this, we need to use a FieldSelector to grab the appropriate downstream cluster.

[v2.9] Fix delete init node for RKE2 clusters

---

extensions/provisioning/creates.go

In the last iteration of release testing, automation for scaling custom clusters was failing. Upon further investigation, the annotation used appends the hexadecimal number to the private IP address.
That needs to be removed in order for it to consistently work, this PR snips that part of the IP address.

[v2.9] Fix internal IP annotation for custom cluster deletion

---

extensions/rke1/nodetemplates/aws/create.go
extensions/rke1/nodetemplates/aws_config.go
extensions/rke1/nodetemplates/azure/create.go
extensions/rke1/nodetemplates/azure_config.go
extensions/rke1/nodetemplates/harvester/create.go
extensions/rke1/nodetemplates/harvester_config.go
extensions/rke1/nodetemplates/linode/create.go
extensions/rke1/nodetemplates/linode_config.go
extensions/rke1/nodetemplates/vsphere/create.go

In the Rancher UI, the expected workflow for RKE1 nodetemplates is that a user uses an existing cloud credential ID. Our automation does not reflect this and bypasses creating a cloud credential. This is not realistic to what customers do, so this small PR fixes that.

[v2.9] Fix RKE1 nodetemplates to include cloud credentials

---

extensions/rke1/nodetemplates/aws/create.go
extensions/rke1/nodetemplates/aws_config.go
extensions/rke1/nodetemplates/azure/create.go
extensions/rke1/nodetemplates/azure_config.go
extensions/rke1/nodetemplates/harvester/create.go
extensions/rke1/nodetemplates/harvester_config.go
extensions/rke1/nodetemplates/linode/create.go
extensions/rke1/nodetemplates/linode_config.go
extensions/rke1/nodetemplates/vsphere/create.go

Backport of https://github.com/rancher/shepherd/pull/194.

[v2.8] Fix RKE1 nodetemplates to include cloud credentials

---

extensions/charts/cisbenchmark.go
extensions/charts/config.go
extensions/charts/payloads.go
extensions/charts/ranchergatekeeper.go
extensions/charts/rancheristio.go
extensions/charts/ranchermonitoring.go
extensions/charts/verify.go
extensions/charts/vsphereoutoftree.go
extensions/rke1/nodetemplates/vsphere/create.go
extensions/rke1/nodetemplates/vsphere_config.go

supports: https://github.com/rancher/rancher/pull/45792
updated the way that pulling data from the vsphereConfig works, and added some functionality around upgrading + validating charts.

adding support to upgrade out-of-tree charts for rke1 vsphere

---

clients/rancher/v1/client.go

This is to give the client more of chance to make sure the schema has been successfully loaded.

Adjust steps, do allow more time to load the schema.

---

pkg/wrangler/context.go

https://github.com/rancher/qa-tasks/issues/1443
**Issue**:
The DownStreamClusterWranglerContext function is currently not handling sessions correctly. When this function is called, it passes nil for the session parameter, resulting in a panic when objects are created on the downstream cluster using wrangler client.
**Solution**:
- Add a session attribute to the Context struct
- Update the NewContext function to initialize the session attribute
- Modify DownStreamClusterWranglerContext to use the stored session
**2.8 Backport PR**: https://github.com/rancher/shepherd/pull/244

Refactor context to store session for downstream context creation

---

extensions/clusters/clusters.go
extensions/upgradeinput/config.go
extensions/upgradeinput/load.go

As part of the QA task, we are refactoring the upgrading package to follow the best practices that packages such as `provisioning` and `snapshot` follow. When refactoring, it was agreed upon to have `kubernetes_test.go` perform the pre and post upgrade checks instead of `workload_test.go`. That way, one test runs all of the operations.
How it currently is, you have to run 3 individual tests that all pertain to one Kubernetes upgrade. This is being addressed in the r/r PR. For shepherd, we need to update the `LoadUpgradeKubernetesConfig` to ensure that the parameters found in `LoadUpgradeWorkloadsConfig` are being referenced.
This way, the `kubernetes_test.go` does not need to have to call two separate configs, which is making the refactor overly complicated.

[v2.10] Update LoadUpgradeKubernetesConfig for upgrade refactor

---

extensions/clusters/clusterconfig.go
extensions/provisioning/creates.go
extensions/provisioninginput/config.go

With this PR we can pass docker version in `cattle-config` which can be used for installing docker on RKE1 custom cluster nodes.
In order to pass docker version, provide below field in the config:
```
provisioningInput: 
rke1CustomClusterDockerInstall:
installDockerURL: "https://releases.rancher.com/install-docker/<version-number>.sh"
```
This change is for the AMIs that doesn't have docker pre-installed and are used in docker and OS checks.

[v2.9] Add docker install support for RKE1 custom cluster

---

extensions/clusters/clusterconfig.go
extensions/provisioning/creates.go
extensions/provisioninginput/config.go

With this PR we can pass docker version in `cattle-config` which can be used for installing docker on RKE1 custom cluster nodes.
In order to pass docker version, provide below field in the config:
```
rke1CustomClusterDockerInstall:
installDockerURL: "https://releases.rancher.com/install-docker/<version-number>.sh"
```
This change is for the AMIs that doesn't have docker pre-installed and are used in docker and OS checks.

[v2.7] Add docker install support for RKE1 custom cluster

---

clients/rancher/client.go

Purpose: To add the user to the client so functions have an easy way to access the user the client that created the client without having to pass that user from the test layer down to the function using it (which can be a headache)

Add the user field to rancher clients.

---

extensions/kubectl/command.go

Changed kubectl Command function to use a ProxyDownstream steve cliente by cluster
Backports:
[v2.9](https://github.com/rancher/shepherd/pull/266)
[v2.8](https://github.com/rancher/shepherd/pull/268)
[v2.7](https://github.com/rancher/shepherd/pull/267)

<main> Fixed pod logs streaming error

---

extensions/workloads/template.go

Small PR that adds a Windows conditional check when scaling RKE2 machinepools up and down. This is applicable only for vSphere node driver clusters that have a Windows worker(s).

[Main] Add Windows support for scaling nodepools

---

extensions/cloudcredentials/aws/create.go
extensions/cloudcredentials/azure/create.go
extensions/cloudcredentials/cloudcredentials.go
extensions/cloudcredentials/digitalocean/create.go
extensions/cloudcredentials/google/create.go
extensions/cloudcredentials/harvester/create.go
extensions/cloudcredentials/linode/create.go
extensions/cloudcredentials/vsphere/create.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/providers/providers.go

Convert V3-->V1 objects and also move the loadConfig call outside of the cloud credentials create as it is bad practice to:
1. Hardcode a load config in functional logic that gets reused (reduces reusability)
2. Combine crud operations. (in this case get and create)

[2.9] Credentials update

---

extensions/cloudcredentials/aws/create.go
extensions/cloudcredentials/azure/create.go
extensions/cloudcredentials/cloudcredentials.go
extensions/cloudcredentials/digitalocean/create.go
extensions/cloudcredentials/google/create.go
extensions/cloudcredentials/harvester/create.go
extensions/cloudcredentials/linode/create.go
extensions/cloudcredentials/vsphere/create.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/providers/providers.go

Convert V3-->V1 objects and also move the loadConfig call outside of the cloud credentials create as it is bad practice to:
1. Hardcode a load config in functional logic that gets reused (reduces reusability)
2. Combine crud operations. (in this case get and create)

[2.8] Update cloud credentials

---

extensions/cloudcredentials/aws/create.go
extensions/cloudcredentials/azure/create.go
extensions/cloudcredentials/cloudcredentials.go
extensions/cloudcredentials/digitalocean/create.go
extensions/cloudcredentials/google/create.go
extensions/cloudcredentials/harvester/create.go
extensions/cloudcredentials/linode/create.go
extensions/cloudcredentials/vsphere/create.go
extensions/defaults/defaults.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/providers/providers.go

Convert V3-->V1 objects and also move the loadConfig call outside of the cloud credentials create as it is bad practice to:
1. Hardcode a load config in functional logic that gets reused (reduces reusability)
2. Combine crud operations. (in this case get and create)

[2.7] Credentials update

---

extensions/clusters/kubernetesversions/all.go

[2.9] updating sortReleases key=minor version instead of rancherMinorversion

---

extensions/clusters/kubernetesversions/all.go

[2.7] updating sortReleases key=minor version instead of rancherMinorversion

---

extensions/clusters/eks/eks_cluster_config.go

Adds support for a different k8s version on EKS nodegroup than used on control-plane.
This allows to define an invalid EKS cluster under rancher which is needed for negative testing of Hosted Providers operators.
If the nodegroup k8s version is not defined it will use the same version as for control-plane so it should be backward compatible.

Add support for setting k8s version in EKS NodeGroup

---

clients/corral/config.go
clients/corral/corral.go

airgap cluster creates weren't working properly when specifying multiple pools with separate / mixed roles. This PR fixes that behavior by setting parity with the other cluster create functions, specifically using existing logic for selecting the right poolRole and quantity.

update createCorral to run separately from wait & create to enable parallel corral jobs

---

extensions/clusters/clusters.go
extensions/etcdsnapshot/etcdsnapshot.go

port of https://github.com/rancher/shepherd/pull/304

[2.8] improve snapshot creation and validation

---

pkg/config/config.go
pkg/config/operations/operations.go
pkg/config/operations/permutations/example_test.go
pkg/config/operations/permutations/permutations.go

Purpose: 
1. To enable permuting of all fields in the cattle config so we can move forward with OS testing automation
2. To lay some of the groundwork for replacing/deprecating provisioning/permutation

Generic Permutations

---

pkg/config/config.go
pkg/config/operations/operations.go
pkg/config/operations/permutations/example_test.go
pkg/config/operations/permutations/permutations.go

backport of https://github.com/rancher/shepherd/pull/279

[2.9] Generic Permutations

---

clients/corral/corral.go

Corral file wait should account for the nil return value from `os.Stat`, which is the state if the file doesn't exist. Currently, the separated command solution makes recurring runs fail because it doesn't wait for the file.
Account nil return value from `os.Stat`, update to debug flag which gives more output for corral creation.

[Main] Fix corral file wait and update the debugging option

---

clients/corral/corral.go

Corral file wait should account for the nil return value from `os.Stat`, which is the state if the file doesn't exist. Currently, the separated command solution makes recurring runs fail because it doesn't wait for the file.
Account nil return value from `os.Stat`, update to debug flag which gives more output for corral creation.

[2.10] Fix Corral File Wait and Update Debugging Option

---

clients/corral/corral.go

Corral file wait should account for the nil return value from `os.Stat`, which is the state if the file doesn't exist. Currently, the separated command solution makes recurring runs fail because it doesn't wait for the file.
Account nil return value from `os.Stat`, update to debug flag which gives more output for corral creation.

[2.9] Fix corral file wait and update the debugging option

---

clients/corral/corral.go

Corral file wait should account for the nil return value from `os.Stat`, which is the state if the file doesn't exist. Currently, the separated command solution makes recurring runs fail because it doesn't wait for the file.
Account nil return value from `os.Stat`, update to debug flag which gives more output for corral creation.

[2.8] Fix corral file wait and update the debugging option

---

clients/harvester/client.go
clients/harvester/config.go

https://github.com/rancher/qa-tasks/issues/468
currently, we don't have a way to write automation for harvester using the framework. 
harvester's API is based on rancher's steve. In this PR I've introduced a harvester client that wraps steve and catalog clients, introduced a new harvesterConfig, similar to how rancherClient is setup. 
We played around with wrapping Steve's API/client directly, but since harvester will need the catalog client as well, giving harvester its own client makes more sense in the long run + to support any use cases their team may have. 
Also played around with simplifying the copy-paste logic between rancher and now harvester clients. But this may make more sense to do if we have to introduce another client that uses most of rancher's API which I don't know of a …

Add harvester Client

---

clients/rkecli/state.go

Back port of https://github.com/rancher/shepherd/pull/356

[2.9]Update rke state file

---

clients/rancher/client.go

It is not currently possible to create a rancher Client without relying on Shepherd's configuration file load mechanism which generates Config structs as needed.
Small refactor to the rancher client's `client.go` which pulls out the majority of the client creation logic into a separate function and adds the `NewClientForConfig` function which takes a *Config directly.
~~Tested locally within the rancher/dartboard project, but have not run any existing tests elsewhere.~~
Ran two rounds of tests both utilizing the new client creation function as well as the default client creation function
There should be no regressions as the flow of the `NewClient` function has not been modified.
Backports:
- #311 
- #312
- #378

Enable creating a rancher client by directly passing a *Config

---

clients/ec2/client.go
extensions/cloudcredentials/aws/create.go
extensions/cloudcredentials/aws_config.go
extensions/cloudcredentials/azure/create.go
extensions/cloudcredentials/digitalocean/create.go
extensions/cloudcredentials/google/create.go
extensions/cloudcredentials/harvester/create.go
extensions/cloudcredentials/linode/create.go
extensions/cloudcredentials/vsphere/create.go
extensions/defaults/namespaces/namespaces.go
extensions/defaults/stevestates/stevestates.go
extensions/defaults/stevetypes/stevetypes.go
extensions/steve/steve.go

Related Rancher PR: https://github.com/rancher/tests/pull/37
Description: 
1. Created a new func for accessing the ec2 client which will be used for accessing ami data for the OS checks
2. Made some changes to the steve.go to fix a bug and to allow it to be more generic so it can be used in a node reboot helper. (this includes updates to all functions that utilze this)
3. Add a few constants for 1. and 2.

Create steve helpers for OS checks

---

extensions/harvester/sakubeconfig.go

https://github.com/rancher/tests/pull/43
Rancher UI specifys a serviceAccountName when generating a kubeconfig from the imported harvester cluster within rancher, using the k8s/clusters api. We need a helper to do this using the apiBaseClient from rancher.

adding extension to get SA'd kubeconfig from harvester via rancher client

---

extensions/users/users.go

I misdiagnosed the cause of the integration test failures in https://github.com/rancher/rancher/pull/49797. I thought that the issue was the namespace being watched, but it was actually the Condition not being satisfied. Reverting.

Undo changes to project namespace

---

clients/harvester/client.go
clients/rancher/client.go
extensions/workloads/pods/pod_status.go

1. Using the `NewClientForConfig()` Rancher client function with `ReLogin()` or other such functions could result in errors, due to the fact that they default to calling the `NewClient()` function which uses Shepherd's config file loading mechanism. Due to the nature of the `NewClientForConfig()` flow expecting a Config struct to be passed directly (bypassing Shepherd's config loading logic entirely), the referenced functions would fail to load the config file when no such config file exists/is in use.
2. The newly added Harvester client had no mechanism to bypass Shepherd's config file loading mechanism. 
3. `IsPodReady()` in `pod_status.go` had both a `nil` check and a zero-length check for the `ContainerStatuses` slice, but this is unnecessary since a `nil` slice has length == 0.
1. As …

Add ForConfig functions for functions in Rancher and Harvester Clients

---

clients/rancher/v1/client.go

The current timeout for the creation of rancher clients causes certain tests to fail intermittently. In my testing this morning as well as over the last few releases this doesn't happen very frequently but it still occurs often enough to be a problem. 
Increasing the backoff duration for the client creation. This should allow clients to retry over a longer period of time and should reduce the number of times that this flakiness occurs.
Ran all tests in the following packages multiple times:
* provisioning/rke2
* provisioning/k3s
This shouldn't cause any regressions.

Update Client timeout to fix test flakiness

---

extensions/etcdsnapshot/etcdsnapshot.go

Backport of https://github.com/rancher/shepherd/pull/427.

[v2.12] Extend RKE2/K3s restore snapshot time

---

pkg/nodes/nodes.go

When hooking up the IPv6 GHA workflows, it was noted of a solution that could work for Jenkins and GHA alike to ensure we can pass our tests with bypassing both pipelines IPv6 limitations.
Update the `Node` struct to have `PublicIPv6Address` and `PrivateIPv6Address`. While a small part here, the corresponding `rancher/tests` PR allows for custom clusters to ssh with the IPv4 address while registering with these values.

Add IPv6 params to Node struct

---

clients/ec2/config.go

The current `config.go` does not allow for choosing your own subnet. As part of broader IPv6 support, we need the option to specify an IPv6-only subnet as part of the networking.
Added `AWSSubnetID` parameter.

Add subnetID parameter for EC2
